2021-05-13 14:23:09,896 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-05-13 14:23:09,896 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\jeenx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\instabot\bot\bot.py
2021-05-13 14:23:09,897 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-05-13 14:23:10,451 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2021-05-13 14:23:10,451 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2021-05-13 14:23:10,453 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2021-05-13 14:23:10,453 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
